/// Flutter icons CustomIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData broadsword = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candleholder = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evilcomet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fairy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData halfheart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maskedspider = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocketbow = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlitbomb = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ancientscrew = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boomerang = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bosskey = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bugnet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cape = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dekutree = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fishingpole = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fishmonster = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData koholintegg = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nestedhearts = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ocarina = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slingshot = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swordaltar = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triforce = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
